development:
  adapter: postgresql
  encoding: unicode
  database: emote_development
  pool: 5
  username: michaelmentele
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: emote_test
  pool: 5
  username: michaelmentele
  password: password
